# Generated by Django 4.2.16 on 2024-10-16 17:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0002_pricealert_product_image_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="pricealert",
            name="product_name",
            field=models.CharField(default="Default Product", max_length=255),
        ),
    ]
